# Generated by Django 3.2.19 on 2023-11-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stfcda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
