# Generated by Django 3.2.19 on 2023-11-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stfcda', '0002_auto_20231114_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_trustee',
            field=models.BooleanField(default=False),
        ),
    ]
