# Generated by Django 3.2.19 on 2023-11-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stfcda', '0007_members_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='lk',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='x',
            field=models.URLField(blank=True, null=True),
        ),
    ]
