# Generated by Django 3.2.19 on 2023-11-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stfcda', '0010_css'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='css',
            new_name='CustomCss',
        ),
    ]
