# Generated by Django 3.2.19 on 2023-11-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stfcda', '0011_rename_css_customcss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCss',
        ),
    ]
