# Generated by Django 4.2.5 on 2023-12-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stfcda', '0013_members_is_executive_members_is_nominated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_nominated', models.BooleanField(default=False)),
                ('n_reason', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stfcda.members')),
            ],
        ),
    ]
