# Generated by Django 5.0.1 on 2024-01-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stfcda', '0014_nomination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journalfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Journal', models.FileField(upload_to='uploads/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
