# Generated by Django 5.0.1 on 2024-01-10 07:12

import stfcda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stfcda', '0015_journalfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalfiles',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='journalfiles',
            name='Journal',
            field=models.FileField(upload_to=stfcda.models.generate_file_path),
        ),
    ]
