# Generated by Django 5.0.1 on 2024-01-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stfcda', '0017_volunteerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='home_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
