# Generated by Django 5.0.1 on 2024-01-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stfcda', '0018_volunteerapplication_home_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='home_address',
        ),
    ]
